### ISSUE TITLE
Closure Notification

### ISSUE THREAD

**Issue by amrrs** [bgreenwell/intro-ml-r#1]
Hi, @bgreenwell  Could you please close this issue when the deck is completed, so I get to know? 

Thanks!

**Comment by bgreenwell** [comment]
@amrrs Will do! If I stay on task, they'll be completed by the end of next week.

**Comment by amrrs** [comment]
That's great to know. So far the deck looks awesome and useful!

**Comment by bgreenwell** [comment]
@amrrs Done?!
